/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pireno;

/**
 *
 * @author A06164358
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        panelConversao = new javax.swing.JPanel();
        labelConversaoBinarioParaDecimal = new javax.swing.JLabel();
        labelConversaoBinarioParaDecimal1 = new javax.swing.JLabel();
        fieldDecimal = new javax.swing.JTextField();
        fieldBinario = new javax.swing.JTextField();
        buttonConverterBinario = new javax.swing.JButton();
        buttonConverterDecimal = new javax.swing.JButton();
        labelConvertidoDecimal = new javax.swing.JLabel();
        labelConvertidoBinario = new javax.swing.JLabel();
        labelDoisPontos = new javax.swing.JLabel();
        labelDoisPontos1 = new javax.swing.JLabel();
        panelCalculadora = new javax.swing.JPanel();
        tabCalculadora = new javax.swing.JTabbedPane();
        panelDecimal = new javax.swing.JPanel();
        fieldDecimalCalc1 = new javax.swing.JTextField();
        fieldDecimalCalc2 = new javax.swing.JTextField();
        comboBoxSinalD = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelResultadoDecimalD = new javax.swing.JLabel();
        labelResultadoBinarioD = new javax.swing.JLabel();
        resultadoSinalMagD = new javax.swing.JLabel();
        resultadoC1D = new javax.swing.JLabel();
        resultadoC2D = new javax.swing.JLabel();
        labelBinSimples = new javax.swing.JLabel();
        labelSinalMag = new javax.swing.JLabel();
        labelC1 = new javax.swing.JLabel();
        labelC2 = new javax.swing.JLabel();
        buttonIgualD = new javax.swing.JButton();
        panelBinário = new javax.swing.JPanel();
        fieldBinarioCalc1 = new javax.swing.JTextField();
        fieldBinarioCalc2 = new javax.swing.JTextField();
        comboBoxSinalB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        labelResultadoDecimalB = new javax.swing.JLabel();
        labelResultadoBinarioB = new javax.swing.JLabel();
        resultadoSinalMagB = new javax.swing.JLabel();
        resultadoC1B = new javax.swing.JLabel();
        resultadoC2B = new javax.swing.JLabel();
        labelBinSimples1 = new javax.swing.JLabel();
        labelSinalMag1 = new javax.swing.JLabel();
        labelC3 = new javax.swing.JLabel();
        labelC4 = new javax.swing.JLabel();
        buttonIgualB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabs.setInheritsPopupMenu(true);
        tabs.setName(""); // NOI18N
        tabs.setRequestFocusEnabled(false);
        tabs.setVerifyInputWhenFocusTarget(false);

        labelConversaoBinarioParaDecimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelConversaoBinarioParaDecimal.setText("Conversão Binário para Decimal:");

        labelConversaoBinarioParaDecimal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelConversaoBinarioParaDecimal1.setText("Conversão Decimal para Binário:");

        fieldDecimal.setText("Decimal");
        fieldDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDecimalActionPerformed(evt);
            }
        });

        fieldBinario.setText("Binário");

        buttonConverterBinario.setText("Converter");
        buttonConverterBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConverterBinarioActionPerformed(evt);
            }
        });

        buttonConverterDecimal.setText("Converter");
        buttonConverterDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConverterDecimalActionPerformed(evt);
            }
        });

        labelConvertidoDecimal.setText("Convertido");

        labelConvertidoBinario.setText("Convertido");

        labelDoisPontos.setText(":");

        labelDoisPontos1.setText(":");

        javax.swing.GroupLayout panelConversaoLayout = new javax.swing.GroupLayout(panelConversao);
        panelConversao.setLayout(panelConversaoLayout);
        panelConversaoLayout.setHorizontalGroup(
            panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConversaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConversaoBinarioParaDecimal)
                    .addComponent(labelConversaoBinarioParaDecimal1)
                    .addGroup(panelConversaoLayout.createSequentialGroup()
                        .addComponent(fieldDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonConverterDecimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDoisPontos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConvertidoBinario))
                    .addGroup(panelConversaoLayout.createSequentialGroup()
                        .addComponent(fieldBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonConverterBinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDoisPontos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConvertidoDecimal)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        panelConversaoLayout.setVerticalGroup(
            panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConversaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConversaoBinarioParaDecimal)
                .addGap(45, 45, 45)
                .addGroup(panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConverterBinario)
                    .addComponent(labelConvertidoDecimal)
                    .addComponent(labelDoisPontos1))
                .addGap(68, 68, 68)
                .addComponent(labelConversaoBinarioParaDecimal1)
                .addGap(45, 45, 45)
                .addGroup(panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConverterDecimal)
                    .addComponent(labelConvertidoBinario)
                    .addComponent(labelDoisPontos))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tabs.addTab("Convesão", panelConversao);

        fieldDecimalCalc1.setText("Decimal");

        fieldDecimalCalc2.setText("Decimal");

        comboBoxSinalD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        comboBoxSinalD.setToolTipText("");

        labelResultadoDecimalD.setText("Decimal");

        labelResultadoBinarioD.setText("Binário");

        resultadoSinalMagD.setText("Sinal Magnitude");

        resultadoC1D.setText("Complemento de 1");

        resultadoC2D.setText("Complemento de 2");

        labelBinSimples.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelBinSimples.setText("Binário Simples:");

        labelSinalMag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSinalMag.setText("Sinal Magnitude:");

        labelC1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelC1.setText("Complemento de 1:");

        labelC2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelC2.setText("Complemento de 2:");

        buttonIgualD.setText("=");

        javax.swing.GroupLayout panelDecimalLayout = new javax.swing.GroupLayout(panelDecimal);
        panelDecimal.setLayout(panelDecimalLayout);
        panelDecimalLayout.setHorizontalGroup(
            panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelDecimalLayout.createSequentialGroup()
                        .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDecimalLayout.createSequentialGroup()
                                .addComponent(fieldDecimalCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxSinalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldDecimalCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelBinSimples)
                            .addComponent(labelSinalMag)
                            .addComponent(labelC1)
                            .addComponent(labelC2))
                        .addGap(18, 18, 18)
                        .addComponent(buttonIgualD)
                        .addGap(18, 18, 18)
                        .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelResultadoDecimalD)
                            .addComponent(resultadoC2D)
                            .addComponent(resultadoC1D)
                            .addComponent(resultadoSinalMagD)
                            .addComponent(labelResultadoBinarioD))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelDecimalLayout.setVerticalGroup(
            panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDecimalLayout.createSequentialGroup()
                        .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldDecimalCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldDecimalCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxSinalD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonIgualD)
                            .addComponent(labelResultadoDecimalD))
                        .addGap(18, 18, 18)
                        .addComponent(labelBinSimples)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSinalMag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelC2))
                    .addGroup(panelDecimalLayout.createSequentialGroup()
                        .addComponent(labelResultadoBinarioD, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoSinalMagD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoC1D)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoC2D)))
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        tabCalculadora.addTab("Decimal", panelDecimal);

        fieldBinarioCalc1.setText("Binário");

        fieldBinarioCalc2.setText("Binário");

        comboBoxSinalB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        comboBoxSinalB.setToolTipText("");

        labelResultadoDecimalB.setText("Decimal");

        labelResultadoBinarioB.setText("Binário");

        resultadoSinalMagB.setText("Sinal Magnitude");

        resultadoC1B.setText("Complemento de 1");

        resultadoC2B.setText("Complemento de 2");

        labelBinSimples1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelBinSimples1.setText("Binário Simples:");

        labelSinalMag1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSinalMag1.setText("Sinal Magnitude:");

        labelC3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelC3.setText("Complemento de 1:");

        labelC4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelC4.setText("Complemento de 2:");

        buttonIgualB.setText("=");

        javax.swing.GroupLayout panelBinárioLayout = new javax.swing.GroupLayout(panelBinário);
        panelBinário.setLayout(panelBinárioLayout);
        panelBinárioLayout.setHorizontalGroup(
            panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBinárioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelBinárioLayout.createSequentialGroup()
                        .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelBinárioLayout.createSequentialGroup()
                                .addComponent(fieldBinarioCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxSinalB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldBinarioCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelBinSimples1)
                            .addComponent(labelSinalMag1)
                            .addComponent(labelC3)
                            .addComponent(labelC4))
                        .addGap(18, 18, 18)
                        .addComponent(buttonIgualB)
                        .addGap(18, 18, 18)
                        .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelResultadoDecimalB)
                            .addComponent(resultadoC2B)
                            .addComponent(resultadoC1B)
                            .addComponent(resultadoSinalMagB)
                            .addComponent(labelResultadoBinarioB))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelBinárioLayout.setVerticalGroup(
            panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBinárioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBinarioCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldBinarioCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSinalB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelResultadoDecimalB)
                    .addComponent(buttonIgualB))
                .addGap(18, 18, 18)
                .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResultadoBinarioB)
                    .addComponent(labelBinSimples1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoSinalMagB)
                    .addComponent(labelSinalMag1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoC1B)
                    .addComponent(labelC3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBinárioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoC2B)
                    .addComponent(labelC4))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tabCalculadora.addTab("Binário", panelBinário);

        javax.swing.GroupLayout panelCalculadoraLayout = new javax.swing.GroupLayout(panelCalculadora);
        panelCalculadora.setLayout(panelCalculadoraLayout);
        panelCalculadoraLayout.setHorizontalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCalculadora)
        );
        panelCalculadoraLayout.setVerticalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCalculadora)
        );

        tabs.addTab("Calculadora", panelCalculadora);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConverterBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConverterBinarioActionPerformed
        // TODO add your handling code here:
        //NÃO FUNCIONA AINDA
        String binario = fieldBinario.getText();
        int[] vetorBin = Leitura.StringParaVetorInt(binario);
        int decimal = Conversao.conversaoDecimal(vetorBin);
        labelConvertidoDecimal.setText(String.valueOf(decimal));
    }//GEN-LAST:event_buttonConverterBinarioActionPerformed

    private void buttonConverterDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConverterDecimalActionPerformed
        // TODO add your handling code here:
        int decimal = Integer.parseInt(fieldDecimal.getText());
        String binario = Conversao.conversaoBinario(decimal);
        labelConvertidoBinario.setText(binario);
        
    }//GEN-LAST:event_buttonConverterDecimalActionPerformed

    private void fieldDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConverterBinario;
    private javax.swing.JButton buttonConverterDecimal;
    private javax.swing.JButton buttonIgualB;
    private javax.swing.JButton buttonIgualD;
    private javax.swing.JComboBox<String> comboBoxSinalB;
    private javax.swing.JComboBox<String> comboBoxSinalD;
    private javax.swing.JTextField fieldBinario;
    private javax.swing.JTextField fieldBinarioCalc1;
    private javax.swing.JTextField fieldBinarioCalc2;
    private javax.swing.JTextField fieldDecimal;
    private javax.swing.JTextField fieldDecimalCalc1;
    private javax.swing.JTextField fieldDecimalCalc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBinSimples;
    private javax.swing.JLabel labelBinSimples1;
    private javax.swing.JLabel labelC1;
    private javax.swing.JLabel labelC2;
    private javax.swing.JLabel labelC3;
    private javax.swing.JLabel labelC4;
    private javax.swing.JLabel labelConversaoBinarioParaDecimal;
    private javax.swing.JLabel labelConversaoBinarioParaDecimal1;
    private javax.swing.JLabel labelConvertidoBinario;
    private javax.swing.JLabel labelConvertidoDecimal;
    private javax.swing.JLabel labelDoisPontos;
    private javax.swing.JLabel labelDoisPontos1;
    private javax.swing.JLabel labelResultadoBinarioB;
    private javax.swing.JLabel labelResultadoBinarioD;
    private javax.swing.JLabel labelResultadoDecimalB;
    private javax.swing.JLabel labelResultadoDecimalD;
    private javax.swing.JLabel labelSinalMag;
    private javax.swing.JLabel labelSinalMag1;
    private javax.swing.JPanel panelBinário;
    private javax.swing.JPanel panelCalculadora;
    private javax.swing.JPanel panelConversao;
    private javax.swing.JPanel panelDecimal;
    private javax.swing.JLabel resultadoC1B;
    private javax.swing.JLabel resultadoC1D;
    private javax.swing.JLabel resultadoC2B;
    private javax.swing.JLabel resultadoC2D;
    private javax.swing.JLabel resultadoSinalMagB;
    private javax.swing.JLabel resultadoSinalMagD;
    private javax.swing.JTabbedPane tabCalculadora;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
