/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pireno;

/**
 *
 * @author A06164358
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        panelConversao = new javax.swing.JPanel();
        labelConversaoBinarioParaDecimal = new javax.swing.JLabel();
        labelConversaoBinarioParaDecimal1 = new javax.swing.JLabel();
        fieldDecimal = new javax.swing.JTextField();
        fieldBinario = new javax.swing.JTextField();
        buttonConverterBinario = new javax.swing.JButton();
        buttonConverterDecimal = new javax.swing.JButton();
        labelConvertidoDecimal = new javax.swing.JLabel();
        labelConvertidoBinario = new javax.swing.JLabel();
        labelDoisPontos = new javax.swing.JLabel();
        labelDoisPontos1 = new javax.swing.JLabel();
        panelCalculadora = new javax.swing.JPanel();
        tabCalculadora = new javax.swing.JTabbedPane();
        panelBinario = new javax.swing.JPanel();
        panelDecimal = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        comboBoxMaisOuMenos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelIgual = new javax.swing.JLabel();
        labelResultadoDecimal = new javax.swing.JLabel();
        labelResultadoBinarioD = new javax.swing.JLabel();
        resultadoSinalMagD = new javax.swing.JLabel();
        resultadoC1D = new javax.swing.JLabel();
        resultadoC2D = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabs.setInheritsPopupMenu(true);
        tabs.setName(""); // NOI18N
        tabs.setRequestFocusEnabled(false);
        tabs.setVerifyInputWhenFocusTarget(false);

        labelConversaoBinarioParaDecimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelConversaoBinarioParaDecimal.setText("Conversão Binário para Decimal:");

        labelConversaoBinarioParaDecimal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelConversaoBinarioParaDecimal1.setText("Conversão Decimal para Binário:");

        fieldDecimal.setText("Decimal");
        fieldDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDecimalActionPerformed(evt);
            }
        });

        fieldBinario.setText("Binário");

        buttonConverterBinario.setText("Converter");
        buttonConverterBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConverterBinarioActionPerformed(evt);
            }
        });

        buttonConverterDecimal.setText("Converter");
        buttonConverterDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConverterDecimalActionPerformed(evt);
            }
        });

        labelConvertidoDecimal.setText("Convertido");

        labelConvertidoBinario.setText("Convertido");

        labelDoisPontos.setText(":");

        labelDoisPontos1.setText(":");

        javax.swing.GroupLayout panelConversaoLayout = new javax.swing.GroupLayout(panelConversao);
        panelConversao.setLayout(panelConversaoLayout);
        panelConversaoLayout.setHorizontalGroup(
            panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConversaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConversaoBinarioParaDecimal)
                    .addComponent(labelConversaoBinarioParaDecimal1)
                    .addGroup(panelConversaoLayout.createSequentialGroup()
                        .addComponent(fieldDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonConverterDecimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDoisPontos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConvertidoBinario))
                    .addGroup(panelConversaoLayout.createSequentialGroup()
                        .addComponent(fieldBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonConverterBinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDoisPontos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConvertidoDecimal)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        panelConversaoLayout.setVerticalGroup(
            panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConversaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConversaoBinarioParaDecimal)
                .addGap(45, 45, 45)
                .addGroup(panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldBinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConverterBinario)
                    .addComponent(labelConvertidoDecimal)
                    .addComponent(labelDoisPontos1))
                .addGap(68, 68, 68)
                .addComponent(labelConversaoBinarioParaDecimal1)
                .addGap(45, 45, 45)
                .addGroup(panelConversaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConverterDecimal)
                    .addComponent(labelConvertidoBinario)
                    .addComponent(labelDoisPontos))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tabs.addTab("Convesão", panelConversao);

        javax.swing.GroupLayout panelBinarioLayout = new javax.swing.GroupLayout(panelBinario);
        panelBinario.setLayout(panelBinarioLayout);
        panelBinarioLayout.setHorizontalGroup(
            panelBinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        panelBinarioLayout.setVerticalGroup(
            panelBinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabCalculadora.addTab("Binário", panelBinario);

        jTextField1.setText("Decimal");

        jTextField2.setText("Decimal");

        comboBoxMaisOuMenos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        comboBoxMaisOuMenos.setToolTipText("");

        labelIgual.setText("=");

        labelResultadoDecimal.setText("Decimal");

        labelResultadoBinarioD.setText("Binário");

        resultadoSinalMagD.setText("Sinal Magnitude");

        resultadoC1D.setText("Complemento de 1");

        resultadoC2D.setText("Complemento de 2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Binário Simples:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Sinal Magnitude:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Complemento de 1:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Complemento de 2:");

        javax.swing.GroupLayout panelDecimalLayout = new javax.swing.GroupLayout(panelDecimal);
        panelDecimal.setLayout(panelDecimalLayout);
        panelDecimalLayout.setHorizontalGroup(
            panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelDecimalLayout.createSequentialGroup()
                        .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDecimalLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)))
                            .addGroup(panelDecimalLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxMaisOuMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelIgual)))
                        .addGap(18, 18, 18)
                        .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelResultadoDecimal)
                            .addComponent(resultadoC2D)
                            .addComponent(resultadoC1D)
                            .addComponent(resultadoSinalMagD)
                            .addComponent(labelResultadoBinarioD))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelDecimalLayout.setVerticalGroup(
            panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDecimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMaisOuMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIgual)
                    .addComponent(labelResultadoDecimal))
                .addGap(18, 18, 18)
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResultadoBinarioD)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoSinalMagD)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoC1D)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadoC2D)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tabCalculadora.addTab("Decimal", panelDecimal);

        javax.swing.GroupLayout panelCalculadoraLayout = new javax.swing.GroupLayout(panelCalculadora);
        panelCalculadora.setLayout(panelCalculadoraLayout);
        panelCalculadoraLayout.setHorizontalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCalculadora)
        );
        panelCalculadoraLayout.setVerticalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCalculadora)
        );

        tabs.addTab("Calculadora", panelCalculadora);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConverterBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConverterBinarioActionPerformed
        // TODO add your handling code here:
        //NÃO FUNCIONA AINDA
//        String binario = fieldBinario.getText();
//        int[] vetorBin = Leitura.StringParaVetor(binario);
//        for(int i = 0; i < vetorBin.length; i++){
//            System.out.print(vetorBin[i]);
//        }
//        int decimal = Conversao.conversaoDecimal(vetorBin);
//        labelConvertidoDecimal.setText(String.valueOf(decimal));
    }//GEN-LAST:event_buttonConverterBinarioActionPerformed

    private void buttonConverterDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConverterDecimalActionPerformed
        // TODO add your handling code here:
        int decimal = Integer.parseInt(fieldDecimal.getText());
        String binario = Conversao.conversaoBinario(decimal);
        labelConvertidoBinario.setText(binario);
        
    }//GEN-LAST:event_buttonConverterDecimalActionPerformed

    private void fieldDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConverterBinario;
    private javax.swing.JButton buttonConverterDecimal;
    private javax.swing.JComboBox<String> comboBoxMaisOuMenos;
    private javax.swing.JTextField fieldBinario;
    private javax.swing.JTextField fieldDecimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelConversaoBinarioParaDecimal;
    private javax.swing.JLabel labelConversaoBinarioParaDecimal1;
    private javax.swing.JLabel labelConvertidoBinario;
    private javax.swing.JLabel labelConvertidoDecimal;
    private javax.swing.JLabel labelDoisPontos;
    private javax.swing.JLabel labelDoisPontos1;
    private javax.swing.JLabel labelIgual;
    private javax.swing.JLabel labelResultadoBinarioD;
    private javax.swing.JLabel labelResultadoDecimal;
    private javax.swing.JPanel panelBinario;
    private javax.swing.JPanel panelCalculadora;
    private javax.swing.JPanel panelConversao;
    private javax.swing.JPanel panelDecimal;
    private javax.swing.JLabel resultadoC1D;
    private javax.swing.JLabel resultadoC2D;
    private javax.swing.JLabel resultadoSinalMagD;
    private javax.swing.JTabbedPane tabCalculadora;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
